sudo: false

language: generic

notifications:
  email: false

git:
  depth: 1
  submodules: false

cache:
  directories:
  - $HOME/toolchain
  - $HOME/protobuf
  - $HOME/submodules

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
      - ubuntu-toolchain-r-test
      - git-core
    packages:
      - cmake
      - cmake-data
      - g++-6
      - git

env:
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug -DCHIBIOS_USE_LTO=0"
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug -DCHIBIOS_USE_LTO=1"
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release -DCHIBIOS_USE_LTO=1"

install:
  - bash travis/install-toolchain.sh
  - ls $HOME/toolchain
  - bash travis/install-protobuf.sh
  - ls $HOME/protobuf
  - bash travis/checkout-submodules.sh
  - ls $HOME/submodules
  - export CXX="g++-6" CC="gcc-6"

script:
  - mkdir build
  - cd build
  - cmake $BUILD_TYPE -DTOOLCHAIN_DIR=$TRAVIS_BUILD_DIR/toolchain/gcc-arm-none-eabi-5_4-2016q2 -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/protobuf/bin/protoc -DCMAKE_TOOLCHAIN_FILE=../toolchain-gcc-arm-none-eabi-5_4-2016q2.cmake ..
  - make

branches:
  only:
    - master
