language: generic

notifications:
  email: false

git:
  depth: 3

cache:
  directories:
  - $HOME/toolchain
  - $HOME/eigen
  - $HOME/boost
  - $HOME/protobuf

sudo: false

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

env:
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug -DCHIBIOS_USE_LTO=0"
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug -DCHIBIOS_USE_LTO=1"
  - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release -DCHIBIOS_USE_LTO=1"

install:
  - bash travis/install-toolchain.sh
  - ls $HOME/toolchain
  - bash travis/install-eigen.sh
  - ls $HOME/eigen
  - bash travis/install-boost.sh
  - ls $HOME/boost
  - bash travis/install-protobuf.sh
  - ls $HOME/protobuf

script:
  - mkdir build
  - cd build
  - cmake $BUILD_TYPE -DBOOST_ROOT=$HOME/boost/boost_1_61_0 -DEIGEN3_INCLUDE_DIR=$HOME/eigen/eigen-eigen-07105f7124f9 -DTOOLCHAIN_DIR=$TRAVIS_BUILD_DIR/toolchain/gcc-arm-none-eabi-5_4-2016q2 -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/protobuf/bin/protoc -DCMAKE_TOOLCHAIN_FILE=../toolchain-gcc-arm-none-eabi-5_4-2016q2.cmake ..
  - make
