language: cpp

notifications:
  email: false

git:
  depth: 3

cache:
  directories:
  - $HOME/toolchain

sudo: false

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

install:
  - bash install-toolchain.sh
  - ls $HOME/toolchain

script:
  - mkdir build
  - cd build
  - cmake -DTOOLCHAIN_DIR=$TRAVIS_BUILD_DIR/toolchain/gcc-arm-none-eabi-5_3-2016q1 -DCMAKE_TOOLCHAIN_FILE=../toolchain-gcc-arm-none-eabi-5_3-2016q1.cmake ..
  - make
