language: cpp

notifications:
  email: false

git:
  depth: 3

cache:
  directories:
  - $HOME/toolchain
  - $HOME/eigen
  - $HOME/boost

sudo: false

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

install:
  - bash install-toolchain.sh
  - ls $HOME/toolchain
  - bash install-eigen.sh
  - ls $HOME/eigen
  - bash install-boost.sh
  - ls $HOME/boost

script:
  - mkdir build
  - cd build
  - cmake -DBOOST_ROOT=$HOME/boost/boost_1_61_0 -DEIGEN3_INCLUDE_DIR=$HOME/eigen/eigen-eigen-07105f7124f9 -DTOOLCHAIN_DIR=$TRAVIS_BUILD_DIR/toolchain/gcc-arm-none-eabi-5_4-2016q2 -DCMAKE_TOOLCHAIN_FILE=../toolchain-gcc-arm-none-eabi-5_4-2016q2.cmake ..
  - make
